### ISSUE TITLE
大家要参与书写教程的，请在这里报名。

### ISSUE THREAD

**Issue by daogangtang** [rustcc/RustPrimer#1]
大家要参与书写教程的，请在这里报名。

报名的时候，请按：

认领哪一章（哪几章） + 每一章完成时间

来写。

来来来，一起来，功德无量。

**Comment by marvin-min** [comment]
可以分点小任务，然后安排一个 deadline， 每周回顾一下。敏捷方式来

**Comment by daogangtang** [comment]
大的deadline目前是明年2月29号。你提这个每周回顾的方式，可以。

**Comment by anzhihun** [comment]
多线程我认领了， 谢谢

**Comment by stormgbs** [comment]
我领个： 可变性、拥有权、租借和生命期

**Comment by stormgbs** [comment]
其他的如果没人，我也可以适当代劳~

**Comment by marvin-min** [comment]
@daogangtang 我先领个安装吧。毕竟我还在学习中。

**Comment by daogangtang** [comment]
@marvin-min 安装是3个平台都要写！你那儿有几个平台？

**Comment by marvin-min** [comment]
我有两个 Mac 和 Win 如果 没人的话。我就搞个 linux 的虚拟机也可以。:)

**Comment by daogangtang** [comment]
@marvin-min 好的。你把完成时间定一下。

**Comment by daogangtang** [comment]
@anzhihun 你的完成时间？

**Comment by marvin-min** [comment]
@daogangtang 我2016-1-5

**Comment by qdao** [comment]
我领了13章闭包吧。暂定1月20号前完成。

**Comment by anzhihun** [comment]
@daogangtang 我暂定在1月20日，谢谢。

**Comment by daogangtang** [comment]
@anzhihun ok.

**Comment by wayslog** [comment]
@daogangtang 看了一圈，没人认领基础部分，那我来认领吧。

我认领 ‘基础类型及运算符’ 一章。
另外你这一章里面是不是少了运算符的部分？我预计会加一节来讲他们。 这一章准备在一月25日之前完成。

另外因为我最近刚换到spacemeacs上，所以编辑器我预计会写上spacemacs的内容，预计一月五号之前完成。

**Comment by daogangtang** [comment]
好的

**Comment by daogangtang** [comment]
以上5位已在大纲上标注。

**Comment by cai-lw** [comment]
只会打算法竞赛的来认领个集合类型吧
寒假才能开写，预计春节前交稿

**Comment by daogangtang** [comment]
@cai-lw 建议不错。我添进去。

**Comment by ee0703** [comment]
@daogangtang  可以认领**一个小时的Rust教程**这一章吗，这部分内容可以参考 https://learnxinyminutes.com/docs/zh-cn/rust-cn/ ，时间的话，一个月内，也就是1月20号前

**Comment by JohnSmithX** [comment]
http://yyo.me/post/rust-three-pointers/
之前学习rust的时候更具自己的理解写过指针方面的post
不知道质量怎么样，够不够

**Comment by daogangtang** [comment]
@JohnSmithX 你是要认领哪一章么？请明确说一下哈。

**Comment by daogangtang** [comment]
@ee0703 可以的，我给你标注一下。

**Comment by JohnSmithX** [comment]
9, 16, 27

**Comment by daogangtang** [comment]
@JohnSmithX  完成时间？

**Comment by JohnSmithX** [comment]
@daogangtang 暂定在1月底吧

**Comment by JohnSmithX** [comment]
md有个格式要求嘛，有个范本嘛

**Comment by daogangtang** [comment]
gitbook，你查下资料。github的md格式规范。

**Comment by jessiex** [comment]
我也认领一章: 模块和包系统、Prelude, 时间1月20号以前.

**Comment by daogangtang** [comment]
@jessiex 已添加。

**Comment by qdao** [comment]
突然发现没有写函数的章节。建议加上，或者直接将13章闭包改为函数和闭包。

**Comment by daogangtang** [comment]
@qdao，好的。还是加一章比较好

**Comment by daogangtang** [comment]
@qdao 函数这一章也你来负责哇？

**Comment by qdao** [comment]
@daogangtang  好，没问题。

**Comment by anzhihun** [comment]
建议添加两个目录， 一个src，用于存放代码， 一个image，便于存放截图，大家觉得如何？

**Comment by anzhihun** [comment]
@daogangtang 我把并发和并行也领了吧， 因为多线程我领了，就一起写吧。 截止时间还是1月20日， 谢谢。

**Comment by daogangtang** [comment]
nice

**Comment by tiansiyuan** [comment]
emacs， 1月20日。

**Comment by stormgbs** [comment]
@daogangtang 我再领一个泛型吧，完成时间1月20号。

**Comment by fuyingfuying** [comment]
@daogangtang 可以参考并以翻译book或者其他doc为主吗，我可以认领cargo，或者ffi，或者测试与评测其中一个，时间16-01-31之前

**Comment by daogangtang** [comment]
@fuyingfuying 这个章节要自己写（才符合中国人的语言习惯），可以参考book及其它材料。你自己明确选一个，或者不介意的话，我3个都给你。

**Comment by daogangtang** [comment]
@stormgbs nice.

**Comment by fuyingfuying** [comment]
@daogangtang  那我选cargo相关的两个章节，时间16-01-31之前

**Comment by daogangtang** [comment]
@fuyingfuying 标注了。

**Comment by corykang** [comment]
校对，有吗

**Comment by daogangtang** [comment]
@corykang 校对内部找人，不公开选。

**Comment by andelf** [comment]
噫，我要报名，模式匹配和迭代器。还有校对工作也可以参与。

**Comment by daogangtang** [comment]
@andelf good。

**Comment by imlcl** [comment]
请问是翻译，还是写？

**Comment by anzhihun** [comment]
@imlcl 是写，不是翻译

**Comment by imlcl** [comment]
@anzhihun 目前还缺少一些项目经验

**Comment by andelf** [comment]
最近外出调研上网不便，我的那两部分delay下。sorry

**Comment by tiansiyuan** [comment]
@daogangtang src/ 里面要放哪些例子程序？

**Comment by daogangtang** [comment]
你文档里面用到的，或需要引用的例子代码，可运行的。

**Comment by tiansiyuan** [comment]
35 代码风格

**Comment by zhongke** [comment]
31 Any与反射

**Comment by daogangtang** [comment]
好

**Comment by daogangtang** [comment]
本书章节越来越多啦，心里美滋滋的，大家一齐努力的成果啊。:D

**Comment by wayslog** [comment]
我认领`运算符重载`这一章

**Comment by daogangtang** [comment]
好呐

**Comment by daogangtang** [comment]
大家得加快进度了哦

**Comment by daogangtang** [comment]
麻烦领了任务的，务必在本周内把手头上的pr提上来哈，拜托哦。

**Comment by wangyu190810** [comment]
领取 37.实战篇 三篇任务。

**Comment by daogangtang** [comment]
ok

**Comment by daogangtang** [comment]
web应用开发，建议用iron

**Comment by wangyu190810** [comment]
我写两个把，iron和nickel分别写一下。数据库的连接有没有限定？ @daogangtang

**Comment by daogangtang** [comment]
优先pg，其次mysql哈

**Comment by wayslog** [comment]
#57  大家努力

**Comment by Naupio** [comment]
领养第33章，**常用数据结构实现**，预计3月21号前完成——naupio_zy_huang

**Comment by daogangtang** [comment]
赞！

**Comment by daogangtang** [comment]
@jessiex 你的认领还没完成，请关注并及时回复！

**Comment by jessiex** [comment]
好的

2016-03-08 1:11 GMT-08:00 Daogang Tang <notifications@github.com>:

**Comment by daogangtang** [comment]
??... 已经分配出去给别人了。

**Comment by jessiex** [comment]
看到这个章节已经有了 不好意思 最近一直在出差 比较忙....


2016-03-28 19:22 GMT-07:00 Daogang Tang <notifications@github.com>:

**Comment by daogangtang** [comment]
v1.0 已经发布。关了。
