### ISSUE TITLE
部分采用rust-book-chinese的内容

### ISSUE THREAD

**Issue by peng1999** [rustcc/RustPrimer#10]
关于Rust的语言本身，已经有了一个[Rust Book的中文翻译](https://github.com/KaiserY/rust-book-chinese)，并已加入到Rust官方文档的[链接](http://doc.rust-lang.org/#community-translations)中。
个人认为各个社区项目之间应该是互补的关系，本项目`7. 基础类型和运算符`到`29. FFI`的内容可以直接借用rust-book-chinese的相关内容，并在其基础上进行修改。
这样可使每个社区项目发挥最大功用，并且可以借机改善rust-book-chinese的翻译。

**Comment by daogangtang** [comment]
是的，我更原来的意思是，直接引用他们的一些段落（标注来源），但要有自己的语言特色。毕竟，国外人写的书语法这些还是不够中国味。

**Comment by peng1999** [comment]
那么，是否应该把它添加到`协作规则`里面？

**Comment by daogangtang** [comment]
感觉没必要，说了就死板了，限制了思考空间。
