### ISSUE TITLE
toml和集成测试的关系的小问题

### ISSUE THREAD

**Issue by lucklove** [rustcc/RustPrimer#112]
书中说`集成测试用例写在tests文件夹下并不能直接运行，需要在toml中进行声明`， 但是在我的环境中并非如此，经过试验，只要是tests文件下的rs都会被cargo test执行

**Comment by daogangtang** [comment]
这是哪一章。

**Comment by lucklove** [comment]
https://github.com/rustcc/RustPrimer/blob/master/05-cargo-projects-manager/05-cargo-projects-manager.md 这里

**Comment by wayslog** [comment]
谁来做下测试？

**Comment by wayslog** [comment]
@lucklove 我需要你给出完整的测试结果，以及什么情况下会被执行，什么情况下不会。如果不能，这个bug可能需要等我有空了做一个完整的测试再说

**Comment by lucklove** [comment]
@wayslog OK

**Comment by lucklove** [comment]
@wayslog 似乎是这样的:
1.如果没有在Cargo.toml里定义集成测试的入口，那么tests目录(不包括子目录)下的每个rs文件被当作集成测试入口.
2.如果在Cargo.toml里定义了集成测试入口，那么定义的那些rs就是入口，不再默认指定任何集成测试入口.

**Comment by wayslog** [comment]
@lucklove ，我做了一遍测试，结论和你基本相同。cargo test在Cargo.toml不指定，或者指定多个入口的时候需要手动指定入口才行。

**Comment by wayslog** [comment]
#144  done
