### ISSUE TITLE
vim自动补全插件ycm已经支持rust，能否更新该章节

### ISSUE THREAD

**Issue by KnightCS** [rustcc/RustPrimer#130]
如题，附上ycm链接：https://github.com/Valloric/YouCompleteMe
还有一个使用ycm的博客：http://blog.jwilm.io/youcompleteme-rust

**Comment by daogangtang** [comment]
欢迎提交pr

**Comment by wayslog** [comment]
恩，前几天已经在群里说了这件事。不过忙着release每顾上，慢慢补充吧！

**Comment by KnightCS** [comment]
踩了个坑，折腾了一下午，记录一下。vim识别 *.rs 结尾的文件的时候，会识别成 hercules(不知道是什么类型) 的类型的文件，而不是 rust 文件，解决方法目前只看到一个简单的方法：在 .vimrc 中添加设置：
`autocmd BufNewFile *rs set filetype=rust`
然后世界就美好了。
