### ISSUE TITLE
'e'和‘E'并不是用于小写字母和大写字母格式化

### ISSUE THREAD

**Issue by chinuno-usami** [rustcc/RustPrimer#137]
操作符和格式化字符串中提到
>还有两个比较有用的type是e和E。他们分别是小写字母和大写字母格式化，别在苦逼兮兮的写大小写转换函数了，Rust早帮你设计好了。

我在格式化字符串成小写的时候编译报错
```
error: the trait `std::fmt::LowerExp` is not implemented for the type `str` 
```
查了查[文档](https://doc.rust-lang.org/std/fmt/trait.LowerExp.html)应该是用于转换成科学计数法中`e`的大小写用的

>Format trait for the e character.
The LowerExp trait should format its output in scientific notation with a lower-case e.

**Comment by wayslog** [comment]
My fault ，写的时候脑子抽了……
tks a lot .

**Comment by wayslog** [comment]
搞定 #138
