### ISSUE TITLE
多线程编程，并发，并行目录合并

### ISSUE THREAD

**Issue by anzhihun** [rustcc/RustPrimer#14]
经过最近今天的书写，觉得这三部分的目录需要进一步调整，从问题概念上来说，并发应该是最大，线程和并行更多地是实现手段，所以我打算把这三个放在一个章节里面来写，从而让他们相互之间更加的紧密和连贯，更便于读者阅读和理解，现拟出的目录结构是这样的：
> 
# 24. 并发编程
## 24.5 并行

在内容上，由于是入门级书，所以在这些章节里面我只会介绍在Rust中如何实现，对于更深层次的锁，并发模型探讨不会深入探讨。 

不知道大家对此有什么建议？

**Comment by daogangtang** [comment]
并发和并行理论上是不同的哦。不过你这个组织我挺喜欢。哈

**Comment by anzhihun** [comment]
确实理论上确实不同，但主要是考虑到这本书的情况，先入个门吧，不能往细了写。等把这个完成了，再单独写一本小书，来说rust的并发和并行，还是很有意思的。 没啥问题，我就先按照这个结构来写。

**Comment by daogangtang** [comment]
ok。
