### ISSUE TITLE
增加一章来介绍 multirust 的吧

### ISSUE THREAD

**Issue by Akagi201** [rustcc/RustPrimer#148]
rust 版本管理必备工具.
跟 GVM, pyenv, 等工具还有点差别, 用起来有点奇怪. 可以介绍下

**Comment by wayslog** [comment]
建议增加为节，而不是章。另外，我用Linux，这东西用的比较少……

**Comment by Akagi201** [comment]
@wayslog rust 版本升级这么快, 必须有个管理工具啊. 我是unix系的, 这些管理工具必备, 也跟个人习惯有关, 我不喜欢手动管理, 喜欢用工具.

**Comment by stormgbs** [comment]
建议放到“安装”那一章里。

**Comment by wayslog** [comment]
@Akagi201 ，你来写吧^_^！
我没法实验这个。

**Comment by Akagi201** [comment]
@wayslog 恩, 好, 我在用呢, 我考虑提个 PR 哈.

**Comment by theJian** [comment]
[tokamak](https://github.com/vertexclique/tokamak) 支持 multirust

**Comment by daogangtang** [comment]
群策群力。好喟

**Comment by guanqun** [comment]
除了mutirust，现在还有rustup也可以加入。

**Comment by tennix** [comment]
其实我个人来看，有些变化太快的东西不宜放到书里，放到社区维基里面比较合适 https://wiki.rust-china.org 有空的童鞋欢迎为维基添砖加瓦

**Comment by Akagi201** [comment]
@guanqun redox-os 使用的是multirust

**Comment by Akagi201** [comment]
@tennix 我觉得一个版本管理工具是很重要的东西, 就像如果会用python但不会用 virtualenv 一样, 是一个知识点的欠缺. 至于rust里最好的 版本工具, 可能还没个定数, 不过, 我目前看 multirust 应该说还不错.

**Comment by wayslog** [comment]
any way , 谁有这玩应的经验……俺并没有……

在 2016-04-08 16:31:01，"Bob Liu" <notifications@github.com> 写道：


@tennix 我觉得一个版本管理工具是很重要的东西, 就像如果会用python但不会用 virtualenv 一样, 是一个知识点的欠缺. 至于rust里最好的 版本工具, 可能还没个定数, 不过, 我目前看 multirust 应该说还不错.

**Comment by tennix** [comment]
@Akagi201 官方以前安装是用 rustup.sh，但是由于很多人要同时使用 stable/nightly，而且升级很快，所以有人做了 multirust.sh。后面又有人用 rust 重写了 multirust.sh，现在 rust 版的 multirust 已经被扶正了，放到官方 nursery 里面去了，而且现在有了专门的网站 https://www.rustup.rs 引导用户使用。所以以后肯定是 rustup.rs 来管理了

**Comment by tennix** [comment]
ok，那我今天晚上抽时间把 multirust 介绍加上吧

**Comment by wayslog** [comment]
#171  #172

**Comment by Akagi201** [comment]
@tennix 我提了个PR, 简单的写了一下, 你补充一些rust 包管理的背景信息吧, 我不太了解.

**Comment by tennix** [comment]
@Akagi201 我还是写到 Wiki 上面去了 https://wiki.rust-china.org/multirust
目前官方推荐的 rustup 还处于 early beta，以后可能还有不少变化，所以放 Wiki 适合随时更新
