### ISSUE TITLE
12-02-borrowing_references.md 第二条和第四条有些重复吧？

### ISSUE THREAD

**Issue by lambdaplus** [rustcc/RustPrimer#156]
####总结
1. 借用不改变内存的所有者（Owner），借用只是对源内存的临时引用。
2. 在借用周期内，借用方可以读写这块内存，所有者被禁止读写内存；且所有者保证在有“借用”存在的情况下，不会释放或转移内存。
3. 失去所有权的变量不可以被借用（访问）。
4. 在租借期内，内存所有者保证不会释放/转移/租借这块内存
5. 借用周期满后，所有者收回读写权限
6. 借用周期小于被借用者（所有者）的生命周期。

**Comment by Naupio** [comment]
第四条的确是重复了，而且有点问题，在租借期内，内存所有者保证不会释放/转移/**租借**这块内存，如果是非可变借用，是可以再租借的~
