### ISSUE TITLE
计划重写第四章，补充大量内容

### ISSUE THREAD

**Issue by Naupio** [rustcc/RustPrimer#158]
因为本人计划的新书 rustdatascience 也有rust快速入门，打算 rustprimer 也一起修改，计划走马观花式重写第四章，计划内容如下：（有什么好提议，在下面提出，我还是从 1 开始数数字。。。）
- [x] 4.1 Rust旅程
- [x] 4.2 基础类型
- [x] 4.3 字符串与向量
- [x] 4.4 结构体与枚举
- [x] 4.5 操作流
- [x] 4.6 函数和方法
- [x] 4.7 特性
- [x] 4.8 注释与文档
- [x] 4.9 输入输出流

**Comment by ee0703** [comment]
支持重写，现在的快速入门章节过于简单

**Comment by daogangtang** [comment]
nice

**Comment by daogangtang** [comment]
一鼓作气

**Comment by daogangtang** [comment]
再而衰，三而褐。

**Comment by timzaak** [comment]
恩呢。。。支持。。👍

**Comment by lambdaplus** [comment]
@daogangtang 
再而盛， 三而盈！！

**Comment by wayslog** [comment]
决定了，等大N写完这个就做1.1的release，unsafe的部分不管了

**Comment by wayslog** [comment]
N猫你咋把PR关了？

**Comment by Naupio** [comment]
没有啊，我早上修 12章 的内容时，把这个也提交了。。。

**Comment by Naupio** [comment]
你 没看到第四章多了一个文件夹么

**Comment by wayslog** [comment]
西马达……完成了之后记得把README和SUMARY都更新一下哈
