### ISSUE TITLE
12章高级MOVE的第一个例子貌似没什么意义？

### ISSUE THREAD

**Issue by Matrix-Zhang** [rustcc/RustPrimer#163]
该例子有没有move都不影响运行结果，容易让新手想多

**Comment by Matrix-Zhang** [comment]
建议再加上这里没有MOVE和有MOVE的区别

**Comment by wayslog** [comment]
额……哪一个例子？

**Comment by Matrix-Zhang** [comment]
@wayslog 第十三章，高级MOVE呀，

···
fn	main()	{
				let	x:	i32	=	100;
				let	some_closure	=	move	|i:	i32|	i	+	x;
				let	y	=	some_closure(2);
				println!("x={},	y={}",	x,	y);
}
····

**Comment by Naupio** [comment]
这个例子 x 是 primitive type，这里 move 和不 move 对结果影响都不大。最好加上说明
