### ISSUE TITLE
14-00-overview.md 有处别字

### ISSUE THREAD

**Issue by Levstyle** [rustcc/RustPrimer#164]
## 但没种数据结构都会有其局限性，合理的选型方能维持更好的效率。

但没种 => 但每种

**Comment by lambdaplus** [comment]
我回去pull request一下就好了，昨天改过了，没有提交

**Comment by Naupio** [comment]
下次小错误，特别是错别字，发现了最好自己 PR 一份，避免几个人同时修改了，搞冲突又麻烦 = =~

**Comment by wayslog** [comment]
#169
