### ISSUE TITLE
看见了self，Python程序员不厚道的笑了。

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#181]
要笑也是smalltalk厨笑，笑完轮到self厨笑。。。
不过anyway self用得挺正常的，直接删掉就好

**Comment by wayslog** [comment]
哈哈，大家一起笑～～

**Comment by theJian** [comment]
今天 issue 爆炸了吗? 同一类问题能不能归个类一口气说完

**Comment by wayslog** [comment]
@theJian ，的确爆炸了……

**Comment by wayslog** [comment]
不认可直接删掉的建议……追根溯源在这里并不合适。写一本面向新手的book的话，必要的诙谐我觉得是必须的。追根溯源在这里没意义，因为谁都知道这是个段子~~！so~~

**Comment by wayslog** [comment]
#200
