### ISSUE TITLE
unsafety-rawpointer

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#187]
unsafe*
话说有unsafety这个词吗。。。好像有，但是用的频率比unsafe小多了，也跟书不一致

**Comment by zonyitoo** [comment]
我看到这题目还以为要提一章名字叫 "unsafety" ... 还好是来吐槽的。

**Comment by theJian** [comment]
这么多相似 issue, 可以考虑创建个 Labels `吐槽`了 :laughing:

**Comment by wayslog** [comment]
#200

**Comment by wayslog** [comment]
#200

**Comment by wayslog** [comment]
#200
