### ISSUE TITLE
heap-stack

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#189]
很多面向对象语言会自称"一切皆对象(Everything is an object)"，潜在的意思就是所有值都是 boxed value

无关，实现基于Fob1的语言可以把object塞stack上，因为大小固定（当然method还是塞不上去，因为closure的破事），再说object含义比boxed value大得多

**Comment by daogangtang** [comment]
虽然不严谨，但大体上说法没问题呢。

**Comment by MarisaKirisame** [comment]
明明无关，什么没问题
没理解错在那的，这句话比认为函数式编程就是一切都是函数指针还离谱

**Comment by theJian** [comment]
@MarisaKirisame  提一下你的修改意见吧

**Comment by MarisaKirisame** [comment]
@theJian 直接去掉就是最简单最有效的修改意见。

**Comment by tennix** [comment]
@MarisaKirisame 我觉得这样说没什么问题，因为前面有一个限定词"很多"，带 GC 的面向对象语言如果自称"一切皆对象"的话，那几乎就是意味着所有值都是 boxed value，而不带 GC 的语言比如 C++ 里面并没有自称"一切皆对象"。我书读的少不知道你说的 Fob1 是什么东西，如果拿一些大家都没怎么听说过的非常小众的语言作反例的话，那我也只能干瞪眼了 :eyes:

**Comment by MarisaKirisame** [comment]
First class object calculus
依然是有三点，
1：很多修饰不明确，这个用括号可以改善
2：就算是Java这样的语言也有unboxed value，而Haskell也box了一大推东西-根本上来说，核心问题就是，两者无必然联系，只是很多面向对象语言都有GC而已。
3：“意思”“就是”会带来这是本质只是boxed value的错觉

**Comment by tennix** [comment]
就现实中的实现来说，对象绝大多数是 boxed value，我觉得 Java 里面的基本类型(primitive type)算不上对象。作为一本入门书，没必要追究这么细节的东西，一般 Python/Ruby/JavaScript 这样的动态语言喜欢自称一切皆对象，这里也是针对这些语言来说的，而 C++/Java 则并没有称一切皆对象

**Comment by F001** [comment]
我支持魔理沙，应该把这些有争议的说法删掉。我们不能在书里信誓旦旦地教给别人错误的知识， 因为别人会引用，会被影响。 我们可以深度不够， 可以有漏掉的没写出来的知识点， 但是写出来了的东西应该经得起推敲。 不要为了追求高深， 而把自己拿不准的东西用确定性语气写出来故作高深。

**Comment by zonyitoo** [comment]
我认为不应该把某一种具体实现来描述一种模型，因为这样潜意识里就像给人钦定了在面向对象的实现中，都是Boxed Value一样，但实际上是没有这个限定的。目前的说法肯定是不严谨

**Comment by daogangtang** [comment]
同意大家。

**Comment by tennix** [comment]
#198 保留这句话的大概意思，换成更严谨的说法。主要想让那些从动态语言过来的，明白他们熟悉的对象其背后是怎么回事，与 Rust 有什么区别

**Comment by MarisaKirisame** [comment]
脑残了，Ob1是First order object calculus，first class到底是什么鬼。。。
FOb1是Ob1 + function
