### ISSUE TITLE
multirust -> rustup

### ISSUE THREAD

**Issue by zitsen** [rustcc/RustPrimer#206]
> `rustup`, successor to `multirust` and `multirust-rs` is [now in beta](https://internals.rust-lang.org/t/beta-testing-rustup-rs/3316/50).

`rustup`现在已经可以取代multirust了，包括这些特性：
- **directory overrides**, 特定日期的nightly/指定版本的stable
- **toolchain specification**, `<channel>[-<date>][-<host>]`
- **cross compiling**, `target add`, which is so convenient for cross compiling,
and `update` can now update all - means the targets too.
- most of the commands `multirust` supported.

在实际使用中已经足够稳定了，建议用来替换 `2.iv` 或增加一节介绍此内容。

**Comment by tennix** [comment]
See our wiki page [rustup](https://wiki.rust-china.org/multirust)

**Comment by zitsen** [comment]
> See our wiki page rustup

got it, but still lack in this book.

**Comment by Akagi201** [comment]
@zitsen 我觉得你可以贡献一篇, 可以先跟multirust并列放在一起, 单独再写一篇文章. 如果后面multirust不行了, 可以去掉那个文章就好了

**Comment by wayslog** [comment]
这种有可能改动比较大的组件，暂时不会入书里的。等rustup或者multirust稳定了之后我们可以考虑再添加。
