### ISSUE TITLE
增加一章讲 IO

### ISSUE THREAD

**Issue by tennix** [rustcc/RustPrimer#220]
标准库那章里面的 fs 只是 IO 的一种，可以考虑归并到 IO 里面讲

**Comment by daogangtang** [comment]
你要写吗？

**Comment by tennix** [comment]
可以

**Comment by Naupio** [comment]
我 rewrite 的 quickstart 也有 io 部分，不过我写简单点的，T猫也可以写详细点，包括一些细节的实现
