### ISSUE TITLE
有没有可能在每章最后一节加上单独的习题章节

### ISSUE THREAD

**Issue by ts25504** [rustcc/RustPrimer#221]
像c++ primer这类书的习题也是经典的一部分，设置一些好的习题应该会让这本书效果更好

**Comment by wayslog** [comment]
好想法～～

**Comment by tennix** [comment]
不过想设计好习题是很有难度的

**Comment by alex-marmot** [comment]
强烈支持加上练习章节

2016-04-21 11:47 GMT+08:00 tennix <notifications@github.com>:

**Comment by daogangtang** [comment]
这个是可以的。

**Comment by MarisaKirisame** [comment]
太大，谁来做？
我建议把这issue拆成：
1：contributor必读里面加入：总的来说，每章应该有习题
2：加上N个习题，分别为：对第N章加入习题
这样每个issue都很可行

**Comment by lambdaplus** [comment]
确实需要，看了一堆，结果不知道自己看的有什么用！导致过脑忘！

**Comment by wayslog** [comment]
啊啊啊啊，忙死了……求拆分……最好能联系到章节原作者

**Comment by MarisaKirisame** [comment]
嗯，我这就拆

**Comment by MarisaKirisame** [comment]
至于联系原作者。。。我觉得没必要，毕竟你github watch上一看就看得到
