### ISSUE TITLE
“语法”的滥用

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#227]
书中，“语法”一词在**很多**地方都有更好，更正确的替代品。
我爬了一遍，发现大部分都是一模一样的问题。
1：以“语法”指“语言构造”(language construct)
https://github.com/rustcc/RustPrimer/blob/master/09-match/09-02-pattern.md
https://github.com/rustcc/RustPrimer/blob/master/08-function/08-02-return_value.md
https://github.com/rustcc/RustPrimer/blob/master/06-flow/06-02-condition.md
https://github.com/rustcc/RustPrimer/blob/master/04-quickstart-rewrite-WIP/04-04-struct-enum.md
https://github.com/rustcc/RustPrimer/blob/master/04-quickstart-rewrite-WIP/04-06-function-method.md
https://github.com/rustcc/RustPrimer/blob/master/04-quickstart-rewrite-WIP/04-09-module-attribute.md
https://github.com/rustcc/RustPrimer/blob/master/14-collections/14-02-hashmap.md
https://github.com/rustcc/RustPrimer/blob/master/16-modules/16-01-module.md
https://github.com/rustcc/RustPrimer/blob/master/27-attr-and-compiler-args/27-01-attributes.md
https://github.com/rustcc/RustPrimer/blob/master/34-std/34-03-net.md
https://github.com/rustcc/RustPrimer/blob/master/07-type/07-04-operator-and-format.md
https://github.com/rustcc/RustPrimer/blob/master/07-type/07-02-compound-types.md
https://github.com/rustcc/RustPrimer/blob/master/15-iterator/15-01-iterator.md
https://github.com/rustcc/RustPrimer/blob/master/04-quickstart-rewrite-WIP/04-02-primitive-type.md
也有其他的错法，但是出现次数不多。
2：以“语法”指“一个程序的代码”
https://github.com/rustcc/RustPrimer/blob/master/10-trait/10-01-trait.md
https://github.com/rustcc/RustPrimer/blob/master/15-iterator/15-01-iterator.md
3：以“语法”指“一个语言”
https://github.com/rustcc/RustPrimer/blob/master/30-coding-style/30-01-style.md

这三个做法的问题所在：
3（以“语法”指“一个语言”）：这是1（以“语法”指“语言构造”(language construct)）的加剧版
2（以“语法”指“一个程序的代码”）：也不对，syntax是一个语言里面如何构造term的规则，而不是一个特定的term

> In linguistics, syntax (/ˈsɪnˌtæks/[1][2]) is the set of rules, principles, and processes that govern the structure of sentences in a given language, specifically word order. The term syntax is also used to refer to the study of such principles and processes.[3] The goal of many syntacticians is to discover the syntactic rules common to all languages.
https://en.wikipedia.org/wiki/Syntax

1：一个语言构造比syntax多得多，比如说有type checking type inference compile interpretation等等等等的破事-当然不排除有完全只是syntax的语法糖的存在，然而那情况下语法糖也是更好的选择。

这件事情的发生原因：
我检查了一下，这些文章是出自不同人之手。
我对此提出一个假设：
1：有一个人不小心用错syntax，并搞进书内
2：这本书的读者看到用错了的syntax，然而不知道是错的，就对syntax有错误的认识
3：内些读者对书提交了pr，positive reinforcement达成。
在这里之所以要找原因，不是要找人负责，而是避免下一次相似事件发生。

如何修复：
短期：把用错了的“语法”按照情况改为“语法糖”“语言构造”“语言”“代码”
中期：对syntax进行一定的介绍，使得所有pr的人都能看到并明白正确做法
毕竟，如果有人用错了syntax，很大概率表示以后还会有人用错
长期：使上面的假设不成立
攻击点：
1：防止【读者读完书->提交pr】
弊大于利，不采纳
2：防止【看到xx用错->对xx有错的认识】**建议**对**多次出现**的术语给定义（并且建议给公认的定义，不要以为怎么样就怎么样）
之所以是多次出现，是因为不可能对每个词语进行一次定义，而多次出现本身不严谨，所以没有执行力
如果把“多”换成n，不是理论上不可行，就是管理起来的破事太多（多用了一次术语，我怎么知道到n了）
3：防止【有人把错的东西写进书内】：
3.1防止有人用错：建立提交pr以前需要明白的知识点（可以就是https://github.com/rustcc/RustPrimer/blob/master/36-appendix/36-01-glossary.md，或者另外写wiki），或者是降低pr的feedbackloop，换言之鼓励写一小半就pr进prototype branch中。两者一起用造成的冲突可以通过label解决。
3.2防止用错后进入：使merge pr的过程更严谨，增加reviewer数量/质量/工作量
3.3用错后快速删除：更多reviewer，同时/或者鼓励一般读者，在看书不理解，或者认为书上错了的时候，发issue提问。

**Comment by MarisaKirisame** [comment]
短期修好了，中期长期提出的做法大家商量商量下

**Comment by wayslog** [comment]
唔……我不是学PLT的……所以我对syntax的认识也是有问题的……

**Comment by MarisaKirisame** [comment]
现在不是说这个，是怎么对坑进行预防。。。

**Comment by wayslog** [comment]
没法预防……
合PR之前我们 
```
grep -nri "语法" .
```
好了……
