### ISSUE TITLE
这本书应该基于markdown吗?

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#229]
markdown问题很明显：章节要手动管理，增加新章节要改，然后link之类的也要改
不考虑考虑用一种source生成？

**Comment by wayslog** [comment]
以前也有讨论过用啥写……但是考虑到LaTeX在国内的接受度……
你会，我会，香港会。。。。。但是你不能保证大家都会是不是……
不过考虑用LaTeX重构一下倒是可以在这本书彻底稳定了之后开始。

**Comment by tennix** [comment]
markdown 增加章节的确不方便，比如我现在想加一章 IO，按章节安排的话肯定要放在中间某个地方，这样的话后面的章节编号都得变。可以开个 latex 分支，谁有精力和兴趣就往里面转

**Comment by daogangtang** [comment]
latex我也会，但是现在感觉没这么多精力搞。

**Comment by tennix** [comment]
gitbook 可以自动生成章节编号，所以不要把章节编号硬编码进文件夹、文件名以及 markdown 文件里面。我待会提交一个 PR 把硬编码的章节编号去掉
