### ISSUE TITLE
Sorry, shoulda asked before a pull request

### ISSUE THREAD

**Issue by archae0pteryx** [rustcc/RustPrimer#235]
I translated the README. I don't speak Chinese and some would say my English leaves much to be desired as well however, I still wanted to help.

**Comment by MarisaKirisame** [comment]
I dont get what you mean by "my English leaves much to be desired?"
BTW, what language are you good in? We of course wont mind if people give efforts to others translation...

**Comment by wayslog** [comment]
Anyway , thanks for your cooperation .

**Comment by archae0pteryx** [comment]
It was a joke, "My english leaves much to be desired" =)

**Comment by daogangtang** [comment]
^..^

**Comment by MarisaKirisame** [comment]
I will close this,feel free to open issue of anything!
