### ISSUE TITLE
any

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#267]
fn load_config<T:Any+Debug>(value: &T) -> Vec<String>{
    let mut cfgs: Vec<String>= vec![];
    let value = value as &Any;
    match value.downcast_ref::<String>() {
        Some(cfp) => cfgs.push(cfp.clone()),
        None => (),
    };

```
match value.downcast_ref::<Vec<String>>() {
    Some(v) => cfgs.push_all(&v),
    None =>(),
}

if cfgs.len() == 0 {
    panic!("No Config File");
}
cfgs
```

}
这个例子做了三件事情：
1：两次尝试downcast value，更改cfgs
2：强制一定有一次downcast对
3：返回cfgs
其实直接downcast一次，成功了返回，失败了再downcast试图返回，再失败panic，就可以，更快漂亮。

**Comment by MarisaKirisame** [comment]
其实我估摸着用monadic bind+monad plus就搞得定

**Comment by wayslog** [comment]
工程角度上来说并不能按照你说的方法做。必须要将所有可用情况显示出来，然后最后返回最后的结果或者panic。因为这里下次维护这段代码的人就不一定是你了，不要让人家深入读代码才知道你做啥，这是效率低下的写码方式。所以，能简单粗暴就简单粗暴。

**Comment by MarisaKirisame** [comment]
一楼的做法也是explicit的，就算不用monadic bind也是一楼的更好，我过几天写一下（暴露基本上没写过rust的事实

**Comment by wayslog** [comment]
hia hia hia ，干吧跌
