### ISSUE TITLE
关于“数字类型”小节(7.1)的“位数”

### ISSUE THREAD

**Issue by veekxt** [rustcc/RustPrimer#269]
其中
>有人说了，你看我整个i128行不。答，不行，谁家电脑是128位的啊

语言支持的整数位数和cpu位数并没有**直接**联系。这样的吐槽不准确甚至会误导初学者

**Comment by MarisaKirisame** [comment]
嗯，自己pr还是想我pr？

**Comment by veekxt** [comment]
@MarisaKirisame 你pr
