### ISSUE TITLE
闭包是现代编程语言的高级特性

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#272]
不不不，scheme都不知道多老了吧。。。

**Comment by lambdaplus** [comment]
>闭包的概念出现于60年代，最早实现闭包的程序语言是Scheme。之后，闭包被广泛使用于函数式编程语言如ML语言和LISP。很多命令式程序语言也开始支持闭包。

**Comment by MarisaKirisame** [comment]
https://github.com/rustcc/RustPrimer/search?utf8=%E2%9C%93&q=%E9%97%AD%E5%8C%85%E6%98%AF%E7%8E%B0%E4%BB%A3%E7%BC%96%E7%A8%8B%E8%AF%AD%E8%A8%80%E7%9A%84%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7+
我改了怎么样？

**Comment by wayslog** [comment]
改吧……

**Comment by MarisaKirisame** [comment]
等会改，有点不好办，去掉不对留着不对小改也不对，什么时候重写这一段。。。

**Comment by wayslog** [comment]
#353
