### ISSUE TITLE
＂泛式＂疑为＂范式＂

### ISSUE THREAD

**Issue by codeworm96** [rustcc/RustPrimer#281]
在＂初识Rust＂一节中：

> Rust 可以被归为通用的、多泛式、编译型的编程语言

这里的泛式应该指 [Programming_paradigm](https://en.wikipedia.org/wiki/Programming_paradigm) 吧，paradigm翻译为范式更常见一些．

**Comment by MarisaKirisame** [comment]
yes,thx
