### ISSUE TITLE
Contributor必读

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#301]
我觉得我们应该把contributor的注意事项列出来。。。
可以放wiki，可以放书，可以开repo
related: #300 #227

**Comment by wayslog** [comment]
强迫症太可怕了

**Comment by arrowrowe** [comment]
可考虑 `~/CONTRIBUTING` 或 `~/.github/CONTRIBUTING`, 参考 [Setting guidelines for repository contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

推荐 [Textlint](https://textlint.github.io/) 的自动化检查和修复, 有格式约定就能做.
参考已纳入的 [EditorConfig](https://github.com/arrowrowe/textlint-rule-editorconfig) 和昨天刚初始化的 [Mixed Typesetting](https://github.com/arrowrowe/textlint-rule-mixed-typesetting).

总之还是要有约定... 以下重述 #300 部分内容.
- 统一中西文标点使用. 可供参考的统一方式: 1) 全部西文标点; 2) 就近原则.
- 统一约定中西混排之间是否需要空格.
- 统一专有名词的大小写拼写.

参考:
- [中文文案排版指北](https://github.com/mzlogin/chinese-copywriting-guidelines)
- [不仅仅是空格的问题——再谈中西文混排](http://www.geekpark.net/topics/198213)
- [中西文混排](http://blog.acgtyrant.com/chinese-western-mixed-typesetting.html)

**Comment by MarisaKirisame** [comment]
#302 这也可以塞进去

**Comment by MarisaKirisame** [comment]
CONTRIBUTING我个人觉得更好
