### ISSUE TITLE
RustPrimer v1.2.0版本注意事项

### ISSUE THREAD

**Issue by wayslog** [rustcc/RustPrimer#302]
从今天开始，将所有合入主分支的PR请打上  v1.2.0-release 的milestone。方便统计changelog。
请各个管理员合并PR之前记得，不然会造成Changelog漏掉了。

@daogangtang @MarisaKirisame @Naupio @tennix

**Comment by daogangtang** [comment]
ok

**Comment by MarisaKirisame** [comment]
k
