### ISSUE TITLE
release 周期是怎么样的?

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#314]
是按照时间来release还是按照feature来release还是两个都有？如果按照feature来release的话我们就可以给issue加上milestone了

**Comment by wayslog** [comment]
按照feature来

**Comment by MarisaKirisame** [comment]
这样我觉得可以把issue给一个milestone去做

**Comment by wayslog** [comment]
恩……关联上milestone也是可以的，毕竟现在的milestone只是为了统计changelog。
