### ISSUE TITLE
补充说明main函数

### ISSUE THREAD

**Issue by veekxt** [rustcc/RustPrimer#335]
毕竟一开始就会用到的，有必要对main函数做更多地说明，比如：

- 只能返回`()`

- 不接受参数，获取命令行参数的方法与c/c++/java不同

但是我并不知道放在哪里好，所以不pr了

**Comment by wayslog** [comment]
不觉得有单独提出说明的必要性。

第一点， " fn main() {} "的函数声明已经注定了它没有返回值。
第二点， 从命令行获取参数的行为属于标准库行为。在标准库一节中已经有实现。
