### ISSUE TITLE
提前增加对pub/private的说明？

### ISSUE THREAD

**Issue by htfy96** [rustcc/RustPrimer#358]
https://wayslog.gitbooks.io/rustprimer/content/quickstart/struct-enum.html
这里4.4开始就提到了pub/private，但pub/private作用于module直到16.1才介绍。

提前增加一小段说明比较好？第一次阅读到这里的时候对“私有”的含义有些不清楚（“既然默认私有为什么外部可以修改”）

**Comment by Naupio** [comment]
这里是我重写的新章节，是快速入门的章节，本来整个章节就**含糊**的，这个章节只是快速的让新手了解基本的概念和入门，并不包含非常详细的说明。这里涉及的可修改的原因并不是 私有和共有的问题，私有和共有只是给外部接口用的。如果要求 quickstart 章节都全部说清楚，这和完全重新写一本rustprimer是没有区别的。
