### ISSUE TITLE
package.json中test命令问题

### ISSUE THREAD

**Issue by ghKelo** [rustcc/RustPrimer#360]
目前test命令为`textlint $(ls --ignore='node_modules')`，这对非Linux用户很不友好。
想不到什么好的方法，或许我们可以用gulp/grunt来解决（[gulp-textlint](https://github.com/textlint/gulp-textlint)/[grunt-textlint](https://github.com/textlint/grunt-textlint)）?

**Comment by wayslog** [comment]
并没有什么问题吧，毕竟大部分用户还是来看书的。
contributor的话用git带的git bash就可以了。

**Comment by ghKelo** [comment]
OK，那就先close
