### ISSUE TITLE
添加rustup.rs相关内容

### ISSUE THREAD

**Issue by Librazy** [rustcc/RustPrimer#370]
multirust 已经不再更新了

> Note: multirust is not actively maintained. Migrate to [rustup.rs](https://github.com/rust-lang-nursery/rustup.rs)

**Comment by wayslog** [comment]
who can do it ……
俺不用muiltirust的……

**Comment by axlrose** [comment]
https://lug.ustc.edu.cn/wiki/mirrors/help/rust-static ustc源还是不错的，收录了 rust-static
export RUSTUP_DIST_ROOT=https://mirrors.ustc.edu.cn/rust-static
