### ISSUE TITLE
Error of one Snippet in `unsafe-rawpointer/raw-pointer.md`

### ISSUE THREAD

**Issue by arrowrowe** [rustcc/RustPrimer#385]
[unsafe-rawpointer/raw-pointer.md](https://github.com/rustcc/RustPrimer/blob/master/unsafe-rawpointer/raw-pointer.md)

```
$ cat sample.rs 
fn main() {
  let mut x = 2;
  let y = &x as *mut i32;
}

$ rustc sample.rs 
sample.rs:3:11: 3:25 error: casting `&i32` as `*mut i32` is invalid
sample.rs:3   let y = &x as *mut i32;
                      ^~~~~~~~~~~~~~
error: aborting due to previous error
```

> 创建一个裸指针：
> ```rust
> let a = 1;
> let b = &a as *const i32;
> 
> let mut x = 2;
> let y = &x as *mut i32;
> ```

**Comment by Librazy** [comment]
`let y = &mut as *mut i32;`

**Comment by arrowrowe** [comment]
@Librazy saw your PR. thanks.
