### ISSUE TITLE
本书的定位是？

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#411]
这本书假不假设对面会编程？如果会，假设会什么？C/C++/Java/Go/Whatever/js？
这本书是单纯的介绍rust是怎么样的语言，还是引领着读者去，以rust为载体，感受一种/多种编程方式（比如Software Foundation，比如SICP，比如ADoP，比如TAOCP（尽管我很看不起里面那奇怪的语言）），还是两者皆有之？

**Comment by MarisaKirisame** [comment]
我建议大家踊跃讨论：一本书没有灵魂，就只是一推文章的集合。
我先抛砖引玉一下，我认为这本书可以着重于static typing对于写程序带来的各种好处（spec，bug catching，speedup），然后可以说Axiomatic Semantic, CSP, Type-Driven Developement等，换句话说以rust为载体，展示static typing的优秀之处，展示type如何帮助你写程序，这是个空白：ADoP，SICP，HTDP等，都没有一个expressive的静态类型系统，而CPDT，SF又离普通人太远。这是个空白，我们应该进入。
我们的例子应该往这方面倾斜（比如给你一个需求，如何选择接口的类型），后面也可以讲一些同样rigor的东西，互补互成（比如Axiomatic Semantic based programming，比如CSP？）

**Comment by daogangtang** [comment]
沙沙，我感觉我hol在不住你说的那些东西 。当初我们定位就是给有 c/c++ 基础的同学学习的。

**Comment by Naupio** [comment]
我赞成定位也是有其他语言基础再学习 rust 的人~我也是照着这个来写的，比如有 C/C++/Python/Haskell任一语言基础的人~

**Comment by lambdaplus** [comment]
罩不住那么多的特性呀，实现需求有多钟方案，到底用哪个？感觉看了一大堆，写时却无从下手！

深受python只有一种解决方案的影响啊！摔

**Comment by wayslog** [comment]
我是按照有Python／CPP／C／Golang 基础的人写的，并不是完全给小白的。说真的，小白不适合这个预言。。。

**Comment by SmartXiaoMing** [comment]
友情支持！

**Comment by johan-sun** [comment]
我觉得还是应该针对有c++基础，展现其对于c++的优势。rust的ownership 很大程度上改善了c++对象所有权管理上的不足。
**而且我认为介绍rust特性的时候就应该那c++的反面例子来对比，来说明为啥要这样设计。指出编译时期发现问题远比运行时发生错误要好**，**为了安全，损失编程灵活性是值得的**。 

至于函数式编程范式的那一套理论的东西，我不是很懂，但并不反感拿一定篇幅来介绍，但是我觉得这不是重点。毕竟Haskell/Scala等语言也有相应的特性吧。rust的定位就是系统级语言，所以我觉得就应该展示他对于其他系统级语言的优势（差不多就是c++了）。

**以rust为载体，感受一种/多种编程方式**，我觉得不是很合适，因为普通人感受多种编程方式的过程中，发现他大部分时间都在和编译器做斗争，然后大部分时间都在思考，为啥我这样写不行。

**Comment by marvin-min** [comment]
@daogangtang 为什么不考虑 java ruby python 之类的啊。 c c++真的回来学习么？深表怀疑~

**Comment by RyanKung** [comment]
@johan-sun 并不认为`Rust`需要通过比较`C++`来证明自己的好/优势，因为`C++`坏得众所周知。

**Comment by fenglingdingdang** [comment]
即使是有动态编程语言基础，在面对rust内存管理部分的时候依然可能比较吃力，让毫无基础的人看懂不太现实

**Comment by biluohc** [comment]
@johan-sun ，那就真变成只适合学过cpp的人阅读了。。从c，py等其它语言来的面对大量cpp大概会直接放弃。

**Comment by wayslog** [comment]
@biluohc ，C++应该是CS科班出身的必备科目吧……至少国内是这样。所以C++基础这个，问题应该不算很大。

**Comment by wayslog** [comment]
结论：初级，最好有点语言基础的，C++基础的最好。
