### ISSUE TITLE
章节号没了

### ISSUE THREAD

**Issue by veekxt** [rustcc/RustPrimer#412]
似乎（不确定）是因为用了gitbook3.0.0，章节号消失了

**Comment by Naupio** [comment]
@veekxt 文件章节号是故意删除掉的，方便，方便更改和整理章节~当时我们工作组做了很多讨论~最后决定删掉章节号的硬编码。

**Comment by veekxt** [comment]
我没表达清楚，
我是说在线阅读的版本章节号码没了。
在gitbook2.x版本，是会自动生成章节号的，这也是去掉硬编码的原因之一。
但是现在3.0.0似乎不会生成了（可能需要额外的配置），对比https://wayslog.gitbooks.io/rustprimer/content/ 和
https://veekxt.gitbooks.io/rustprimer-fork-/content/ 的左侧目录的区别
就明白我要说什么了。

**Comment by tennix** [comment]
GitBook 3.0.0 默认禁掉了 TOC https://github.com/GitbookIO/gitbook/issues/1323
