### ISSUE TITLE
包和模块这章关于 super self的解释加入类似路径的说明更形象些

### ISSUE THREAD

**Issue by axlrose** [rustcc/RustPrimer#419]
What about the self? Well, by default, use declarations are absolute paths, starting from your crate root. 
self makes that path relative to your current place in the hierarchy instead. 
There’s one more special form of use: you can use super:: to reach one level up the tree from your current location.
 Some people like to think of self as . and super as .., 
from many shells’ display for the current directory and the parent directory.

self看成当前目录 **.**
super看成父类目录 **..**

**Comment by tennix** [comment]
用目录类比的话，很容易让新手把目录和mod概念直接映射到一起了，而与很多语言里面不一样的是 Rust 里面的 mod 并没有规定物理上是怎么存储的

**Comment by wayslog** [comment]
thanks anyway
