### ISSUE TITLE
带有特性约束的泛型函数使用单态 (monomorphization)， 所以它是静态派分的 (statically dispatched)。

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#424]
出自于
https://doc.rust-lang.org/book/traits.html
我认为这句话应该去掉，原因有5。
1:trait本来就是ad-hoc polymorphism
2:generic是parametric polymorphism
3:两个也没有相加互相抵消：polymorphism的原意是一个东西可以作用于不同类型上，而trait约束了generic还有多个类型满足的情况有，还很多
4:dispatch本来就是在有polymorphism时才有的词，如果没有polymorphism，dispatch一词毫无意义
5:单从教育层面也不够好，比如static dispatch是什么前面就没描述，只是单单的把很多对此书的读者来说意义不明的词糊在一起

**Comment by daogangtang** [comment]
原书写得确实也有很多模棱两可的地方

**Comment by MarisaKirisame** [comment]
哦，查了查，是【单态化】不是【单态】
