### ISSUE TITLE
一切运动都必须深入到广大的群众里面去

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#428]
我们应该鼓励读者提出的反馈&提问，不然很难知道书_教育_（不是技术，技术我还能抓）上出了什么问题
比如说什么地方看了不知道有没有用，什么地方看了没懂，什么地方无聊，什么地方重复等等
这些不是我等早就会rust的人知道的，只有真正需要这本书的人，才知道这些地方那出了问题

**Comment by wayslog** [comment]
可以什么方式更好呢？online的下面有提供disscusion的地方，其他的，留个邮件如何？

**Comment by MarisaKirisame** [comment]
提供survey可以，口头鼓励一定要做，毕竟大部分人都面生只会潜水
其实我更鼓励由老司机带，换句话说隔段时间新人X向一个会rust的导师Y汇报，有问题也问Y，然后Y找时机对X做survey
一是进展程度好track，如果X跟群体互动，就是多个人掌握X的信息，无法知道X什么时候快什么时候慢，也有面生潜水党
二是基础问题问一个人就够了，无需劳烦一群人

如果搞的话，我能先带一两个，一周付出2~4小时

**Comment by wayslog** [comment]
大众计划很好。。。然而失败。。。检讨。。。去年确实太忙了。。。没时间弄这个。。。。
