### ISSUE TITLE
考虑下该不该/如何以project guide这本书

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#429]
换句话说，
1：一开始就给出这本书的目标：教你搞XX（或者XX，YY）
2：配置开发环境开始
3：引入一些新特性，给XX加入功能
4：由于代码量增长过于复杂，引入一些新特性，对XX进行重构
5：重复3-4

pro：
有什么用一眼就能看出来，立竿见影
动手记东西效率高
exercise呼之跃出
其他rust书没这么做的，一下就stand out

con：
例子不好找：AI PL我觉得还可以，但是不算很好
多个做也可以，然而我没想出什么好的搭配
算法库也可以，然而太无聊，项目内做几个算法/数据结构玩玩linear type就够了，光做算法估计不会太吸引人

**Comment by wayslog** [comment]
大N已经有想法做基因相关的编程了，我在探索系统／中间价的编程，Mike在专注web。我们三个各有不同的方向，再加上莎莎你的AL PL方向的书作为进阶，感觉可以再出一个系列。
* 《Rust for Generic》 
* 《Rust for Web》
* 《Rust for Server Side》
* 《Rust for AL/PL 》

**Comment by MarisaKirisame** [comment]
Genetic Programming还是Generic？两者天差地别

**Comment by MarisaKirisame** [comment]
还有我的想法不是【进阶】而是【intro】如此搞

**Comment by wayslog** [comment]
sorry ， Gene is right
