### ISSUE TITLE
规范方面

### ISSUE THREAD

**Issue by MarisaKirisame** [rustcc/RustPrimer#507]
遍历一遍全书太麻烦
所以还是赶紧把各个规范搞出来，然后再遍历一次
之后，
以后要微改规范就不遍历了，写在读者能看到的地方让读者对不符合的提issue

**Comment by wayslog** [comment]
遍历吧。。。没人来做哟。。。只能wayslog慢慢啃了。。。至于规范嘛。。。wayslog说的就是规范咯，当然我会尊重一些常见的规范的。。。
