### ISSUE TITLE
目录层级结构不对

### ISSUE THREAD

**Issue by loggerhead** [rustcc/RustPrimer#517]
整个的层级缩进了一层，应该缩回来。比如：

    1.1. Introduction
    1.2. 初识Rust

应该是：

    1. Introduction
    2. 初识Rust

**Comment by wayslog** [comment]
唔……谁会搞这个……
貌似是我为了接入某个应用搞的。。。

**Comment by wayslog** [comment]
@loggerhead ,你会不会搞这个？

**Comment by loggerhead** [comment]
@wayslog 不会弄……不过可以通过修改 book.json 来规避这个问题：

```json
{
    "lang":"zh-cn",
    "pluginsConfig": {
    	"theme-default": {
    	    "showLevel": true
    	}
    }
}
```
