### ISSUE TITLE
move语义不严谨

### ISSUE THREAD

**Issue by tagstar** [rustcc/RustPrimer#518]
**可以把资源的所有权(ownership)从一个绑定转移（move）成另一个绑定，这个操作同样通过let关键字完成**
这句话，应该不严谨，因为赋值也会产生所有权转移,
如下：

fn main()
{
    let x = vec![1, 2];
    let mut y = vec!{3, 4};
    y = x;
    println!("{:?}", x);
}
error: use of moved value: `x` [--explain E0382]

**Comment by wayslog** [comment]
哪里不严谨？ 第一句话说的就是赋值，因为在 Rust 中，默认的赋值和 `return` 表达的都是 `move` 语义，第二句话说的才是(re)assign的情况……
