### ISSUE TITLE
Still working on this?

### ISSUE THREAD

**Issue by archae0pteryx** [rustcc/RustPrimer#537]
Just checking if i should do some more google translate for ya...?

**Comment by wayslog** [comment]
Of course you could start a transeltion work now.
I see the pull request you had ever raised, but unfortunately we are working hard at the same time, so your translation branch is left behind by the master. That's the reason why it's closed.
And now, it's the time to translate the book.
We all would acknowledge for your work.

**Comment by BanjoFox** [comment]
Do you guys need more help? 
I am a native English speaker.

**Comment by archae0pteryx** [comment]
I sure am! I've been a bit busy lately but i hope to have some time this weekend to dig back in. thanks for keeping me in the loop.

**Comment by archae0pteryx** [comment]
Ok. I cleaned up my old branches. I added -b en_us-master and removed "en-us" for clarity. i also added a changelog to track the translation so other english speakers don't keep translating things that have already been done. I will put together a PR here in a min.
