### ISSUE TITLE
rust.cc 是否 已经下线？

### ISSUE THREAD

**Issue by samrayleung** [rustcc/RustPrimer#546]
如题，rust.cc 一直无法访问，不知道是否已经下线。国内缺乏比较好的 Rust 社区，所以有此疑问。

**Comment by TakWolf** [comment]
看看这个：
https://www.rust-lang-cn.org/

**Comment by samrayleung** [comment]
这个论坛我也有看过，但是，平心而论，并不活跃。所以我平时逛的都是 reddit.com/r/rust

**Comment by TakWolf** [comment]
国内哪个技术论坛比较活跃？
基本都是这个状态

**Comment by samrayleung** [comment]
https://emacs-china.org/ 相信全世界的 Emacs 用户都不会很多，中国的相对就更少了。但是即使这样，这个论坛还是很活跃的。
