### ISSUE TITLE
1.18错误处理第二个unwrap那部分编译不了

### ISSUE THREAD

**Issue by jinglunchn** [rustcc/RustPrimer#551]
impl<T, **E: ::std::fmt::Debug**> Result<T, E> {   //E: ::std::fmt::Debug是什么意思
    fn unwrap(self) -> T {
        match self {
            Result::Ok(val) => val,
            Result::Err(err) =>
              panic!("called `Result::unwrap()` on an `Err` value: {:?}", err),
        }
    }
}

**Comment by Librazy** [comment]
这个是标准库的源代码 https://github.com/rust-lang/rust/blob/d21ec9b4efd1da012979b050bc0a0426fe45fcdf/src/libcore/result.rs#L712
