### ISSUE TITLE
应该有一个书写风格规范。

### ISSUE THREAD

**Issue by t123yh** [rustcc/RustPrimer#6]
比如在英语、数字和中文之间应该有一个空格。如此之类的细节值得注意，不然后期修改会很麻烦。

**Comment by daogangtang** [comment]
能否有成套的建议？列出来，直接pr，merge

**Comment by andelf** [comment]
gitbook 呗？

**Comment by zonyitoo** [comment]
这个问题可以改用 LaTeX 来解决。最终出版时用 Markdown 显然是不行的

**Comment by marvin-min** [comment]
Hello,大家还是先把内容写出来吧。别的我们再议好不好呀。目前 gitbook（MarkDown）支持导出各种电子格式。我想这已经解决了很大问题了。
