### ISSUE TITLE
第三十七章的数据库操作，可能要延迟

### ISSUE THREAD

**Issue by wangyu190810** [rustcc/RustPrimer#61]
原因是因为我使用postgresql的连接库postgres。在自己实践时出现问题，所以弄了两天了依旧没有解决，当然我希望有人如果操作过这个部分，可以自己尝试写一写这个，我自己弄完不知道什么时候了，求大神填坑。当然也可能是我自己用户不熟悉导致的。
为了不耽误整体的进度，如果有人正好操作过这些，希望能写一下简单的教程，填坑一下。

**Comment by daogangtang** [comment]
ok，有心人关注下。

**Comment by daogangtang** [comment]
已完成。
