### ISSUE TITLE
RustPrimer/07-primitive-type/07-02-strings.md

### ISSUE THREAD

**Issue by fengbol** [rustcc/RustPrimer#76]
let x:&'static str = "hello world";

let y:String = x.to_string();
println!("{}", y);
y.push_str(", world");
println!("{}", y);
编译不通过，需要给y加mut

**Comment by daogangtang** [comment]
@wayslog

**Comment by wayslog** [comment]
get

**Comment by wayslog** [comment]
#85 可以关闭了
