### ISSUE TITLE
Deref 这章的措辞不够严谨

### ISSUE THREAD

**Issue by F001** [rustcc/RustPrimer#78]
关于这句话：“所以，它实际上在解引用之前做了一个引用的归一化操作。”

这个概念貌似是自创的， 在其它文档中没见过“归一化”这个说法。 触发自动Deref的条件是这样的： 如果实际使用的类型是T，但是需要的类型是U，那么编译器会检查T是否能隐式转换为U，检查规则如下：

```
HasCoercion(T, U):

  if HasBasicCoercion(T, U) then
      true
  else if T = &V and V: Deref<W> then
      HasCoercion(&W, U)
  else if T = &mut V and V: Deref<W> then
      HasCoercion(&W, U)
  else if T = &mut V and V: DerefMut<W> then
      HasCoercion(&W, U)
  else
      false
```

参考资料： https://github.com/rust-lang/rfcs/blob/master/text/0241-deref-conversions.md

建议删除“归一化”的说法。

**Comment by daogangtang** [comment]
我个人的理解上，确实是做了这个“归一化”事情。只是外部文档没有这样说。这些代码，其实也是这个意思。你觉得呢？归一化这个，显得更形而上。
