### ISSUE TITLE
建议重写 24-05-parallel 这章

### ISSUE THREAD

**Issue by F001** [rustcc/RustPrimer#79]
@wayslog 关于“并行”这章，首先感谢做出的努力。但是，我觉得这里举的例子不够恰当，完全没有体现出Rust标榜的“安全的并发”这一设计理念。
这个例子误用了全局变量，充满了`unsafe`代码，没有将内部实现细节和外部抽象接口很好的分离。不是一个恰当的例子。

建议： niko 最近的这个项目就很有意思 https://github.com/nikomatsakis/rayon ， 我们可以使用这个项目的示例代码，给新手演示一下，简洁的api， 安全的并发， 以及不错的高性能， 完美得到统一。

**Comment by tennix** [comment]
@F001 赞，babysteps 上面也有一系列[博客(]http://smallcultfollowing.com/babysteps/blog/2016/02/19/parallel-iterators-part-1-foundations/)讲 parallel iterator 实现的，不过目前还有一篇没写完，过几天应该也出来了，也可以参考一下。要不还是神庙兄改写呗

**Comment by anzhihun** [comment]
@F001 首先更正一下“并行”这个章节不是@wayslog写的，是我写的。 年前写的， 本来是打算写一个mapreduce的例子替换的它，但一直时间紧，如果你有兴趣，或者其他有兴趣，可以重写一下。

**Comment by F001** [comment]
好的，我领下这个任务。

**Comment by daogangtang** [comment]
赞！

**Comment by wayslog** [comment]
今天才看到这个……完美的躺枪

**Comment by daogangtang** [comment]
你该说什么好

**Comment by stormgbs** [comment]
@daogangtang  赞，我也觉得需要补充和改进下，写的不够细致。我这几天有空再补充下。回头大家再看看。

**Comment by daogangtang** [comment]
把e猫那个文章精华加进去。

**Comment by daogangtang** [comment]
这一章是rust区别与其它语言的精华，我希望能写好一点
