### ISSUE TITLE
目录结构调整

### ISSUE THREAD

**Issue by wayslog** [rustcc/RustPrimer#93]
1. 章节安排不合理，`Result和Option`一章应该往前靠，至少在集合类型之前
2. 对章节的子小节的文件，其文件名不应该带有本章章节号，不然不利于重构本书。

建议在 1.0 release 之前修正这两个问题，现在先不要动，不然很有可能造成git的三路合并。

**Comment by daogangtang** [comment]
可以只改readme目录的顺序
